# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2a9a5af836b2aa110f98e837551b100d82bc50842e7a4a07bb6360164ad1af97da1be80f4570ed042b786d0d768f2028b73115bfb74926193a278215b9678a41

test:
  secret_key_base: 065edcebe83a90a8e78d604cba3903c4c1854927f60fd276133f44d8dccf252143a4a0454e0a5f259a8bf25929a3dd235d5d3d46c9e07554a7f5e4f765ffccb1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
